server:
  port: 8081


spring:
  application:
    name: fraud

  datasource:
    driver-class-name: org.postgresql.Driver
    username: murad
    password: password
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
